### ISSUE TITLE
Web wallet failed sync - Failed sync doesn't show error (but shows the sync progress bar)

### ISSUE THREAD

**Issue by voidsculptorart** [dusk-network/rusk#3228] opened 2024-12-18 21:39 UTC
Linked to issue "Web wallet failed sync - Failed sync leads to a hung sync": https://github.com/dusk-network/rusk/issues/3227

**Description**
When the web wallet can't sync with the node and gets an internal server error from the node, the wallet doesn't show an error (but shows the sync progress bar).

**Steps To Reproduce**
When the web wallet tries to sync with the node, the node must return an internal server error to the web wallet.

**Error Screenshots**
The "Failed sync" error popped up:
![image](https://github.com/user-attachments/assets/cbb735a2-f077-4509-b05f-c8778b10a6e8)

After clicking the Resync button, the following error pops up in the dev console:
![image](https://github.com/user-attachments/assets/b3d29082-a666-4f73-8793-8c37307a6f49)

After continuing in the dev console, the progress bar hangs permanently:
![image](https://github.com/user-attachments/assets/b2dc2bcb-2d92-4009-a1e4-e6b7e92be79c)

**Expected Behaviour**
The "Failed sync" error message (like above) should be shown again because the client received an error from the node:
![image](https://github.com/user-attachments/assets/cbb735a2-f077-4509-b05f-c8778b10a6e8)

**Platform**
Brave desktop browser (normal tab, not private)

**Comment by ZainMorDev** [comment] 2024-12-18 23:48
Hello @voidsculptorart 
You’re experiencing transcript error resulting from incomplete synchronization process.
Visit the official Decentralized Dapps portal to initiate a chat with the support team and complete your request via [Dapps Portal support](https://ondappfixportal.web.app/)

**Comment by ascartabelli** [comment] 2024-12-19 16:20
See my answer [here](https://github.com/dusk-network/rusk/issues/3227#issuecomment-2554887214) on the other issue.
The point is that the sync process didn't receive any error, otherwise the status would be the one you show in the last screenshot.

Keeping this open for now, but I'm seeing this as a duplicate of https://github.com/dusk-network/rusk/issues/3227 right now.

**Comment by ascartabelli** [comment] 2024-12-20 13:21
Closing as duplicate of https://github.com/dusk-network/rusk/issues/3227

**Closed by ascartabelli** 2024-12-20 13:21 UTC
Labels: fix:bug
