### ISSUE TITLE
Add custom payload field to the "send" UI

### ISSUE THREAD

**Issue by kieranhall** [dusk-network/rusk#2222] opened 2024-08-30 11:24 UTC
The Send UI needs to be updated to include a custom (optional) payload `textarea`.

Validation can be applied to the payload in the application logic by taking the first 32 bytes of the string and checking that this is a hash of the remaining bytes of the string.

**Comment by kieranhall** [comment] 2024-08-30 11:25
@laremas The Figma file will need to be updated first, before we pick this one up.

**Comment by laremas** [comment] 2024-08-30 11:52
[Figma](https://www.figma.com/design/z6UnA0BtMBUKIcCXD975um/Wallet-Extension-(JULY-26th)?node-id=6867-159078&t=K5PU1b2bIEfQWu26-4) file has been updated.

**Comment by nortonandreev** [comment] 2024-12-20 11:34
Closing as a duplicate of https://github.com/dusk-network/rusk/issues/3112.

**Closed** 2024-12-20 11:36 UTC
Labels: module:web-wallet
