### ISSUE TITLE
CLI wallet should perform standalone operations without running Rusk

### ISSUE THREAD

**Issue by autholykos** [dusk-network/rusk#507] opened 2022-01-31 18:00 UTC
**Describe what you want implemented** 
Following operations should not require to run an instance of Rusk: 
- Export BLS Key Pairs on an AES-encrypted JSON file
- Retrieve own public spend key

**Describe "Why" this is needed**
This is needed for facilitating devops and testing operations

**Describe alternatives you've considered**
Keeping a running Rusk instance as a prerequisite

**Comment by t00ts** [comment] 2022-02-01 08:36
Duplicate of #499

**Closed** 2022-02-02 09:32 UTC
Labels: area:wallet, mark:testnet
