### ISSUE TITLE
Migrate to piecrust

### ISSUE THREAD

**Issue by robinmario90** [dusk-network/rusk#765] opened 2022-11-02 10:21 UTC
**Summary**
We should port rusk to use piecrust instead of rusk-vm. This is necessary to make full use of the new contract ABI and the improvements to speed and disk-space efficiency provided by piecrust.

**Possible solution design or implementation**
To complete this issue the following issues will need to be addressed:

 #757
 #758
 #759
 #764
 #761
_Link actual issues to this epic_

**Additional context**
This epic is designed to keep track of the progress of porting rusk to use piecrust and should be closed when such an effort is done.

**Comment by ureeves** [comment] 2022-11-04 13:45
Closing as duplicate of #760

**Closed by ureeves** 2022-11-04 13:45 UTC
Labels: Epic, mark:next
