### ISSUE TITLE
rusk-wallet: moolight-unstake returns gas limit lower than minimum 75000 

### ISSUE THREAD

**Issue by nth1686** [dusk-network/rusk#2674] opened 2024-10-15 13:12 UTC
Transaction ready. Proceed? · Yes
Staking address: 244h5qgZaU8S6GttT5zL1K56xecr4YrddWLd5HzByB15uhcJS5V6J1m5H5ewTTHJj3ywTMUrbFV8Ku1QpMEVPziLu3fK67Ry7xrcBcpsmG7CnYH2ww1JoVA92Ar22hPjVFZ3
Rusk error occurred: 500 Internal Server Error: gas limit lower than minimum 75000
account-data received!

**Comment by HDauven** [comment] 2024-10-15 13:54
Duplicate of #2654, resolved by #2657

**Closed by HDauven** 2024-10-15 13:54 UTC
Labels: fix:bug
