### ISSUE TITLE
Cannot disable the state persistence

### ISSUE THREAD

**Issue by herr-seppia** [dusk-network/rusk#584] opened 2022-02-18 10:46 UTC
**Describe the bug**
The state is automatically persisted at each state change

**To Reproduce**
Remove any `persist` call to the state.

**Expected behaviour**
The state data file should not grow

**Additional context**
The problem seems that microkelvin `persist_default` is called by canonical during the `set_contract_state` in mint

```
  14:        0x10b8ec06f - microkelvin::persist::Persistence::persist_default::h8295abe237927956
  15:        0x10b8d77a3 - microkelvin:🔗:Link<C,A>:🆔:hc05b47a8724bfb60
  16:        0x10b8da321 - <microkelvin:🔗:Link<C,A> as canonical::canon::Canon>::encoded_len::h6139e4aabc85a695
  17:        0x10b8e4604 - canonical::implementations::<impl canonical::canon::Canon for [T; N]>::encoded_len::h50aa48afc272b491
  18:        0x10b8eba43 - <transfer_contract::transfer::TransferContract as canonical::canon::Canon>::encoded_len::h3a347b566069625e
  19:        0x10b87da7d - <T as canonical::canon::EncodeToVec>::encode_to_vec::hac752a384a06f6c4
  20:        0x10b8964d5 - rusk::state::RuskState::set_contract_state::hfd914436110037a9
  21:        0x10b8971a8 - rusk::state::RuskState::mint::ha45450bcf1735cd5
  ```

Introduced with
https://github.com/dusk-network/microkelvin/pull/103/commits/a32a5caf4421bf567199fc8fd9461b5e7769377e#diff-5ded0f9d91b4f8d412e18911958630a24845bac320f5fcde7e45d16c4582c5adR156-R159

**Comment by ZER0** [comment] 2022-04-14 13:46
I'm going to close it as wontfix since this is working as intended (for the time being: persist always the state is the only way we can make microkelvin and canonical working in the current stack. The VM2 should solve this issue too).

**Closed** 2022-04-14 13:46 UTC
Labels: status:wontfix, fix:bug
