### ISSUE TITLE
Define the source of `gas_limit` and `gas_price` for `Transfer::execute`

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/rusk#187] opened 2021-02-12 15:08 UTC
The current definition of gas limit and price is currently arbitrary in the tests of the transfer contract.

We need to have a clear understanding on who is the actor responsible for that definition and where the information should live

**Comment by ZER0** [comment] 2021-02-24 09:48
Duplicate of #195

**Closed by ZER0** 2021-02-24 09:48 UTC
Labels: status:duplicate, team:Core
