### ISSUE TITLE
negative blocktimes in Nocturne

### ISSUE THREAD

**Issue by sanderdms** [dusk-network/rusk#2051] opened 2024-07-30 16:48 UTC
**Describe the bug**

At times, the block explorer shows negative block times. Specifically, the next block has a timestamp earlier than the previous block, which is incorrect and results in negative block times.

**To Reproduce**

Open the block explorer.
Navigate to a block that shows a negative block time.
Observe the timestamp of this block and the preceding block.

**Expected behaviour**

The timestamps of blocks should always be in ascending order, with each subsequent block having a timestamp that is equal to or later than the previous block. Negative block times indicate a problem with how block timestamps are being recorded or displayed.

**Logs/Screenshot**

Logs: [Attach logs related to block generation or explorer errors]
Screenshot: [Attach a screenshot showing the negative block times in the block explorer]
Platform

Architecture: [e.g., ARM, x86]
OS: [e.g., Linux, Windows]
Browser: [e.g., Chrome, Firefox]
Additional context

The issue might be related to how block timestamps are synchronized or recorded.

<table>
	<tr>
		<th>blk_timestamp</th>
		<th>blk_height</th>
		<th>blk_hash</th>
		<th>meta_process</th>
		<th>blk_time</th>
	</tr>
	<tr>
		<td>2024-07-30 14:25:58</td>
		<td>2674813</td>
		<td>2fe33ad6fe00fc1a7623a1b2f7245954149df87ffac6b09c015d90580699c9c8</td>
		<td>TAIL_EU1_NOCTURNE_DEV</td>
		<td>-1402</td>
	</tr>
	<tr>
		<td>2024-07-30 00:43:31</td>
		<td>2662915</td>
		<td>b46275a5f4d2cca64e875c916b2f8aed275c290f4c5f35d7f5fcb422ca70bcf7</td>
		<td>TAIL_EU1_NOCTURNE_DEV</td>
		<td>-1396</td>
	</tr>
	<tr>
		<td>2024-07-28 22:25:53</td>
		<td>2640187</td>
		<td>c773b2bc0e2d3d4cab2d38519623513dbc3a5a2b848258256d8da324bee8e5d7</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1389</td>
	</tr>
	<tr>
		<td>2024-07-27 21:35:24</td>
		<td>2618965</td>
		<td>8065dec3d2e3cf4b12610e1caad11bc97786b141ccbd706d93759113ea70f982</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1380</td>
	</tr>
	<tr>
		<td>2024-07-27 03:46:57</td>
		<td>2604196</td>
		<td>e65db8c7ebc924aa38c0c93bab0b94da8414eca168afe4d7fbdab3624524f8f8</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1374</td>
	</tr>
	<tr>
		<td>2024-07-27 20:28:44</td>
		<td>2618008</td>
		<td>bbf119415fe69b5c7276f44fb0350a9a1e9566b48f3a0bc8fdbaa48660c66f93</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1372</td>
	</tr>
	<tr>
		<td>2024-07-26 18:45:30</td>
		<td>2596464</td>
		<td>f2d118c313543252b7f09bd59208d69c9791d7e7298e3cfc97cfa30192857fb3</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1371</td>
	</tr>
	<tr>
		<td>2024-07-26 10:05:56</td>
		<td>2589059</td>
		<td>0f9b4a08452d6af664379a94c69950341109808fe02b48726486a61542e38d9a</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1368</td>
	</tr>
	<tr>
		<td>2024-07-25 22:54:45</td>
		<td>2579329</td>
		<td>7744cbbcdd1fb6887a1632a4933a6bb2e45606eb3e6f126642fb643112a64045</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1363</td>
	</tr>
	<tr>
		<td>2024-07-25 21:03:29</td>
		<td>2577683</td>
		<td>6c63d67cef41b0bed6cf80053bd7f392da18a08ffa26aa6a7b603324324e939a</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1363</td>
	</tr>
	<tr>
		<td>2024-07-25 23:11:53</td>
		<td>2579559</td>
		<td>fde2e7f0c619809839aa82db0c31046f55f84440600e4b8bdada09f7f762343c</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1363</td>
	</tr>
	<tr>
		<td>2024-07-25 12:17:15</td>
		<td>2570314</td>
		<td>4cd31e4a554000ae97050f3378b285c12af1dd50c0bdf1ef97801649b989d44f</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1358</td>
	</tr>
	<tr>
		<td>2024-07-25 03:31:07</td>
		<td>2562811</td>
		<td>c0e723a095829d21080ec79a1f993f581dce3901ed590b4673d5f1f1dba92912</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1356</td>
	</tr>
	<tr>
		<td>2024-07-25 02:12:36</td>
		<td>2561685</td>
		<td>e78f099a812a93be322ef7027d98d12b6049a8e5a3f3c8011b60ae20076ff67a</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1349</td>
	</tr>
	<tr>
		<td>2024-07-24 00:59:44</td>
		<td>2539694</td>
		<td>6b8215c1d8284d280707bf98624509a318c613399f3a26eb879496a19df14921</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1347</td>
	</tr>
	<tr>
		<td>2024-07-24 01:15:45</td>
		<td>2539960</td>
		<td>cb1b71908b1afc7d6b1a41ce29cc7c90a641cb97890d1db1cf0766ca32bf890c</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1347</td>
	</tr>
	<tr>
		<td>2024-07-23 01:37:24</td>
		<td>2518888</td>
		<td>bce346298ce30b62c7677d0d30218b894b987eda481e375b7d8264193dd0c008</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1339</td>
	</tr>
	<tr>
		<td>2024-07-22 16:52:56</td>
		<td>2511149</td>
		<td>36349dbab34dedb82c4a7818c18e0b7273e69f556948322fb893a0f9c0e8205d</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1335</td>
	</tr>
	<tr>
		<td>2024-07-23 19:09:27</td>
		<td>2534446</td>
		<td>da1b04ed2b498e91ff04a68ac80b5bd7020ade92ab734bdb18570817cdcbc359</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1335</td>
	</tr>
	<tr>
		<td>2024-07-22 10:51:34</td>
		<td>2505995</td>
		<td>239c52d80f3b4345d14fd35fd30e450c82bc6ecf4dc499d6921788ff9af8f0b7</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1334</td>
	</tr>
	<tr>
		<td>2024-07-22 02:40:07</td>
		<td>2498616</td>
		<td>d5da9291b74ffa49bf3e7f7c779e625535408d4ca0342a943851b87df051de24</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1331</td>
	</tr>
	<tr>
		<td>2024-07-21 16:29:02</td>
		<td>2489679</td>
		<td>fb08affe50b47857cb48b69d636c684e8ad4b1aa0ca6256ccf44315c2aa59fc2</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1327</td>
	</tr>
	<tr>
		<td>2024-07-21 09:46:54</td>
		<td>2483809</td>
		<td>f51d9c010cf8ade8cc2049c2ae1ac7b3b5bf7f118a432cece2802cb18512ab3e</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1325</td>
	</tr>
	<tr>
		<td>2024-07-21 08:11:02</td>
		<td>2482404</td>
		<td>8f24fe43a2097284b313f7c42cb2777af6db5cc9a0e172a43a22b6198b067252</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1325</td>
	</tr>
	<tr>
		<td>2024-07-21 08:04:39</td>
		<td>2482294</td>
		<td>c427be906097de460690eee023465107cd24b0f721a18be533a4e1a66d4d3496</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1323</td>
	</tr>
	<tr>
		<td>2024-07-20 20:54:11</td>
		<td>2472603</td>
		<td>102eb30c5f674f8a8511e077310e3101afc9522e6c94fa123d17b4f838086e87</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1321</td>
	</tr>
	<tr>
		<td>2024-07-20 18:25:37</td>
		<td>2470498</td>
		<td>ab329480d638226cd9641b12d6bf4794cde4469083eea57202458bd94e85a744</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1320</td>
	</tr>
	<tr>
		<td>2024-07-20 14:26:00</td>
		<td>2466862</td>
		<td>b388ffb2f8a0cd7593d2cc9c08c54452f0cf2467149bc3818b081a7a16b2b134</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1319</td>
	</tr>
	<tr>
		<td>2024-07-20 08:25:13</td>
		<td>2461615</td>
		<td>35be749d7210e0ba04211d9931eb312d1f776e150e2b4667e2332bc1fc34865f</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1316</td>
	</tr>
	<tr>
		<td>2024-07-20 07:52:53</td>
		<td>2461117</td>
		<td>1cffe24d0fc965f5ab3a2712fd8b343de970aec802919c81c2d4e10f024dc8a1</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1316</td>
	</tr>
	<tr>
		<td>2024-07-19 15:27:46</td>
		<td>2446846</td>
		<td>85e69609ad0154df87d6951f77bf2d7ca914b98f632870811cd6c2543c21ad76</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1310</td>
	</tr>
	<tr>
		<td>2024-07-18 20:53:54</td>
		<td>2430778</td>
		<td>aaf600d547db02f1bc7c48e39404ec6184fee76348c008f88beb86b69c7c1c74</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1303</td>
	</tr>
	<tr>
		<td>2024-07-18 13:27:41</td>
		<td>2424292</td>
		<td>76115e20278792bd6b5c1b389c8f26897144e09721638bee3b1b207d9a41942f</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1299</td>
	</tr>
	<tr>
		<td>2024-07-18 03:09:23</td>
		<td>2415431</td>
		<td>123689860a96077a63d26660fef93ef07638ecc02afd09cebf48a056f9578c81</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1298</td>
	</tr>
	<tr>
		<td>2024-07-17 12:48:13</td>
		<td>2402924</td>
		<td>366df73206cc28be9ab15038eb3a7dfa8392160bb50b41560ab67f255f208bf8</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1293</td>
	</tr>
	<tr>
		<td>2024-07-17 08:04:42</td>
		<td>2398854</td>
		<td>e0b42868ba8304f3c948243c0c664123ec648247db557b3f09cf47850be02634</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1291</td>
	</tr>
	<tr>
		<td>2024-07-18 06:43:44</td>
		<td>2418530</td>
		<td>1cd40f80b626874f957f81bbafc8667dee2181e28ae1b8d1287cb8b908359171</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1291</td>
	</tr>
	<tr>
		<td>2024-07-17 05:01:24</td>
		<td>2396263</td>
		<td>b8add0ba7a18fc56237c12b38bab06de2623415efb6b3fec10700f631715f14c</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1290</td>
	</tr>
	<tr>
		<td>2024-07-17 09:16:38</td>
		<td>2399853</td>
		<td>bc3f1cf91a53c7c8ffa1cd1072409d5e30d74afe82e6fd5ab76ad3afcc1417fd</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1290</td>
	</tr>
	<tr>
		<td>2024-07-16 18:05:01</td>
		<td>2386962</td>
		<td>4c260c3ff554fd95c7b5ce5c195bac99a91a898ea4708664b5f65964e3471ac5</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1286</td>
	</tr>
	<tr>
		<td>2024-07-16 04:27:59</td>
		<td>2375301</td>
		<td>06a2589e3b97efe8dce00d5eea5929c16d519a63a5860464b80f44b2073ff8c5</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1281</td>
	</tr>
	<tr>
		<td>2024-07-16 04:16:11</td>
		<td>2375128</td>
		<td>99620c9b83a7f22158c99ca0d0e191ef893dc3bcb436a83845d982e1c3195395</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1281</td>
	</tr>
	<tr>
		<td>2024-07-16 03:05:38</td>
		<td>2374140</td>
		<td>adcaf3e2f6dc19f9a220e75d26e356ed95f86892dddce96772f54c483127e77e</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1280</td>
	</tr>
	<tr>
		<td>2024-07-15 20:56:40</td>
		<td>2368803</td>
		<td>614cc821707e5ca1ff1d82abe1584bb0110b9b3dd26005dc9c8f35f7eb09bf10</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1279</td>
	</tr>
	<tr>
		<td>2024-07-15 19:37:24</td>
		<td>2367709</td>
		<td>f24da417891210bee154f54c52d1129971e674ac38b23e8fb39b7643c09934ec</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1278</td>
	</tr>
	<tr>
		<td>2024-07-17 05:08:32</td>
		<td>2396372</td>
		<td>0b7f9025b8e57d91d5b60ddbf724260e2ee09023ed61fa33a724d10bb50d2e6b</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1277</td>
	</tr>
	<tr>
		<td>2024-07-16 16:39:37</td>
		<td>2385695</td>
		<td>3ae7b29f38291a9f9352cf44af58663f828b1feb1a7b20d53a86825e693ff225</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1276</td>
	</tr>
	<tr>
		<td>2024-07-15 10:43:01</td>
		<td>2360130</td>
		<td>853dd212c57f1054caeeae6afeea457b81a3d8acef5a9e77a10ef82b91cdd670</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1274</td>
	</tr>
	<tr>
		<td>2024-07-15 07:52:45</td>
		<td>2357749</td>
		<td>49aab5e9b82276e2a112c4ed9dddf733826c8ab56454979a02151c8f1bbb94fa</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1274</td>
	</tr>
	<tr>
		<td>2024-07-15 08:41:17</td>
		<td>2358480</td>
		<td>6e513092e245fe51695f7b1f45f36f4eb967959bc1a30a0fedb8b7b2ec6345eb</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1274</td>
	</tr>
	<tr>
		<td>2024-07-15 01:53:21</td>
		<td>2352422</td>
		<td>82fe20ea8f87d1c72499f0045ae21a53e233761f1355017b84f455294953d62f</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1272</td>
	</tr>
	<tr>
		<td>2024-07-14 23:21:15</td>
		<td>2350165</td>
		<td>0b8e81ab249bbb844bedf9772c634e46fe94de8fc75aa10b0e570ec1492134fa</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1272</td>
	</tr>
	<tr>
		<td>2024-07-14 10:41:59</td>
		<td>2338726</td>
		<td>1b64961aab5e6de3864cd762b20ea919fae82adf58e199bef493575ae8772745</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1266</td>
	</tr>
	<tr>
		<td>2024-07-14 17:01:10</td>
		<td>2344400</td>
		<td>75bf3bacf9f24c1ad265225ff85bbf956804bb1bd53bb2ff00c247726168d650</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1262</td>
	</tr>
	<tr>
		<td>2024-07-13 15:29:11</td>
		<td>2321510</td>
		<td>28250cc965a054dfb855dcdea3118583be48b53bf5ae2c7f3d6b47cf8a29e04c</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1260</td>
	</tr>
	<tr>
		<td>2024-07-13 16:26:03</td>
		<td>2322316</td>
		<td>4287ee993ac552675d84409326f7a78f4c2f2d482dac08997fc865766dacca1e</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1260</td>
	</tr>
	<tr>
		<td>2024-07-13 11:58:56</td>
		<td>2318431</td>
		<td>d23397743922437640ff6247081e021bc0a6a3375f447d4788e36bda78b83149</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1259</td>
	</tr>
	<tr>
		<td>2024-07-13 02:23:09</td>
		<td>2310041</td>
		<td>2f83a7afdcb3881b62f5d32704cb14677246c03e66f096f258b71c94053fe3a1</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1256</td>
	</tr>
	<tr>
		<td>2024-07-14 07:19:00</td>
		<td>2335634</td>
		<td>dfe1aa38e2822fadadfc6d0b113f3c3375347f619eb2643d2ee1e8cf2c736644</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1256</td>
	</tr>
	<tr>
		<td>2024-07-13 00:35:11</td>
		<td>2308409</td>
		<td>5df42ca4fb8b6f879316ee443dd351c040cbcbc4466f19cdf6a6a7cbb4cfef9b</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1255</td>
	</tr>
	<tr>
		<td>2024-07-13 00:52:04</td>
		<td>2308684</td>
		<td>3f68bdb44f60b1064b92670ec6601e3660621795989be09e6e370bac35afdf8c</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1255</td>
	</tr>
	<tr>
		<td>2024-07-12 20:54:55</td>
		<td>2305171</td>
		<td>1e9fb708bcc34e13df723e11594a9f449019e657d25b469483bab54f4e6a7500</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1254</td>
	</tr>
	<tr>
		<td>2024-07-12 21:49:58</td>
		<td>2305944</td>
		<td>e88012373444e6d4347e512545e946c368b155f74d7146d1ea6e13492345cab6</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1254</td>
	</tr>
	<tr>
		<td>2024-07-12 17:57:06</td>
		<td>2302519</td>
		<td>62b9a9bf58533921ccb7d1e234f63502e0c05565867ff04ea4a8d38624956726</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1253</td>
	</tr>
	<tr>
		<td>2024-07-12 08:34:05</td>
		<td>2294271</td>
		<td>aff79abe95a09d54bc5e866fd4ff854f3aaf4c9eb24092d2f5a16c377389f5d7</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1250</td>
	</tr>
	<tr>
		<td>2024-07-12 19:47:54</td>
		<td>2304160</td>
		<td>420b23cafa8f99ee45c0078f4c947a7685a6535996a6f4ccd92813cf3e6fc26b</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1249</td>
	</tr>
	<tr>
		<td>2024-07-12 02:12:00</td>
		<td>2288710</td>
		<td>b04952d0b81718876c00a50dbc7d3e3a39ad97c60dcf4b8e78655bf32f6649f3</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1247</td>
	</tr>
	<tr>
		<td>2024-07-11 18:36:01</td>
		<td>2281963</td>
		<td>91bc6805f660190eff64a51545e783be3bd6266e47478cfe0d67584dd0ed6462</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1245</td>
	</tr>
	<tr>
		<td>2024-07-12 13:46:39</td>
		<td>2298783</td>
		<td>f662730fca4d736ab0b371070a820965ffd2185ff2b9e7e553f48116892a2f5e</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1244</td>
	</tr>
	<tr>
		<td>2024-07-11 08:06:49</td>
		<td>2272751</td>
		<td>a55eb85da68ca941b031799b11e9a7fc5f90b1416080c6133e0ed82e5f2aed8a</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1241</td>
	</tr>
	<tr>
		<td>2024-07-11 08:37:39</td>
		<td>2273180</td>
		<td>893e9191564803ee601897a9a2ab2ef41e012bcfdf399d9dc2252f84b3248132</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1241</td>
	</tr>
	<tr>
		<td>2024-07-11 11:43:33</td>
		<td>2276006</td>
		<td>b58e77b2a6c639be6fa1f40dd55317269830794c91446b51966ce8a36d10bcf1</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1235</td>
	</tr>
	<tr>
		<td>2024-07-10 03:31:44</td>
		<td>2250024</td>
		<td>b36e8bf8c4991e592fe47593e4d13783c2dfd767047ff3f716222a4741b9bc76</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1231</td>
	</tr>
	<tr>
		<td>2024-07-09 23:01:49</td>
		<td>2246989</td>
		<td>b3f4fc3cf6e9285388e2aa881bfe2773e477b20c09e1312744e2945c0033c2a9</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1230</td>
	</tr>
	<tr>
		<td>2024-07-09 21:45:47</td>
		<td>2246123</td>
		<td>bb771ed87f63a400e7db6fd126b1b898e90bb4a5e4f885f982a83e0d19c57e77</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1229</td>
	</tr>
	<tr>
		<td>2024-07-10 01:10:32</td>
		<td>2248436</td>
		<td>62465675440a60e7a02db0f1efb8e110224d6c15b17ac206deaf4283517d05a8</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1222</td>
	</tr>
	<tr>
		<td>2024-07-08 13:50:07</td>
		<td>2218503</td>
		<td>6d45edd8689ce8e470464881ea3db45f09dda7554b132574d35f78cb7b9c79ad</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1217</td>
	</tr>
	<tr>
		<td>2024-07-08 06:42:32</td>
		<td>2212233</td>
		<td>a4cb0a934e244d05cd390a2896eae8bd9b7e639d116548b7ebd553a319577764</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1216</td>
	</tr>
	<tr>
		<td>2024-07-07 23:37:19</td>
		<td>2206136</td>
		<td>3e56ca5dc9ab5a44ad9e1d30e529414bec3cd28005c2cef993de8387c80e94d4</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1212</td>
	</tr>
	<tr>
		<td>2024-07-08 01:11:35</td>
		<td>2207524</td>
		<td>636924e32e1dc5fcc4bd2a3514bdf000883974a9775ca15d7ff9e3883f3eb073</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1212</td>
	</tr>
	<tr>
		<td>2024-07-07 18:13:37</td>
		<td>2201261</td>
		<td>75901bc489b431cfa02b3b956a3d698c7c72929cb2710f280e51e6b3f6aa718b</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1211</td>
	</tr>
	<tr>
		<td>2024-07-06 22:25:36</td>
		<td>2184019</td>
		<td>f7bbeda72dd280032756166d44e4c0db7058a372e046e086c63ce24b6535c7b7</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1205</td>
	</tr>
	<tr>
		<td>2024-07-06 20:19:37</td>
		<td>2182213</td>
		<td>c6949fff29b8640046dc2a2001db4608d6fa99390ffbfa66770b5f3b76eaa2d1</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1204</td>
	</tr>
	<tr>
		<td>2024-07-06 01:43:35</td>
		<td>2165943</td>
		<td>0ce54a1d60350b412050291f86aacc335095be46020717d913d20f29f57aeabe</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1197</td>
	</tr>
	<tr>
		<td>2024-07-04 08:23:42</td>
		<td>2130908</td>
		<td>c0ee10e43eb99b0bc73b7c432a9e7f96b30ccb7925c24571f498b1b634f85fc6</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1182</td>
	</tr>
	<tr>
		<td>2024-07-03 22:04:57</td>
		<td>2122141</td>
		<td>f1fe05457bf231274e2c205d1dd112f3ea7e94ff35a318e195be30d98045b151</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1179</td>
	</tr>
	<tr>
		<td>2024-07-02 21:27:06</td>
		<td>2101144</td>
		<td>c9d385c408b6f363fb28edf2b2a42a658f9e588e1864eac7ac5a1c1e2e83fcb0</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1171</td>
	</tr>
	<tr>
		<td>2024-07-02 19:56:20</td>
		<td>2099745</td>
		<td>a3953f2c51ec3462f09ffd38894809dfa915af070793b932bddca50e1108d9c7</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1170</td>
	</tr>
	<tr>
		<td>2024-07-02 07:21:08</td>
		<td>2087828</td>
		<td>872e4b1e80f5701653cfd5ddc2e8d39c50860069151d9c19d2a2d232ca18b80e</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1166</td>
	</tr>
	<tr>
		<td>2024-07-02 03:03:27</td>
		<td>2083949</td>
		<td>b3fc7461a46611da66febeac3ef7cb25330155f904f17e8c44bfcabc4856ed1b</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1163</td>
	</tr>
	<tr>
		<td>2024-07-01 22:11:30</td>
		<td>2079419</td>
		<td>2ad77cd47cfcd829adf35a2f25a78192fbd2972bcf3f5651c24a22437a4ab33c</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1162</td>
	</tr>
	<tr>
		<td>2024-07-01 00:30:23</td>
		<td>2061688</td>
		<td>3353809bb009cac4063295aa751c636b4bbc1842d75692fe065c30e3c0b2cd51</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1155</td>
	</tr>
	<tr>
		<td>2024-06-30 06:50:07</td>
		<td>2048164</td>
		<td>2eec5d4af94f50d09a66624d79ef3ae3666a0774300f097086fdd467cc0fc476</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1148</td>
	</tr>
	<tr>
		<td>2024-06-30 00:11:27</td>
		<td>2042863</td>
		<td>60c141629abf2f9b73a016138a9ce3de82c60a0ad261f2fe91740fb912b2c396</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1145</td>
	</tr>
	<tr>
		<td>2024-06-29 22:59:26</td>
		<td>2041907</td>
		<td>8c3080d9f6063461d03b0a47320ede18868a27ec54f28be963d1e6c082a02251</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1145</td>
	</tr>
	<tr>
		<td>2024-06-29 21:19:40</td>
		<td>2040606</td>
		<td>5320c1be8d20f7bd895bc375d1b9c43dcb5e6438077b62569312c021e6737801</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1144</td>
	</tr>
	<tr>
		<td>2024-06-29 11:23:00</td>
		<td>2032872</td>
		<td>ef791bc9a18fdbf20dff82183465a7b1fd5fe58629c999847aaec28476149e26</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1142</td>
	</tr>
	<tr>
		<td>2024-06-28 11:34:54</td>
		<td>2014488</td>
		<td>e0de4b258350c43d412f91c5662a7e3bbded579c06b7d3127a0f689716a3b012</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1132</td>
	</tr>
	<tr>
		<td>2024-06-27 18:35:54</td>
		<td>1999334</td>
		<td>0b1c953d05040bc8b3884d2e0794025869f3639e32efa8f82809b03f0f4a90d7</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1127</td>
	</tr>
	<tr>
		<td>2024-06-27 06:00:47</td>
		<td>1988399</td>
		<td>0c67bf78464db9f9b76d520f4854e409aa5643c9d1c5bfc91fc6d2a7db079076</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1123</td>
	</tr>
	<tr>
		<td>2024-06-27 03:19:23</td>
		<td>1986004</td>
		<td>86314a149c302ae7a7782350be2247aa78a81d0b34b8292dadd6ed53c86f04cd</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1123</td>
	</tr>
	<tr>
		<td>2024-06-26 20:07:28</td>
		<td>1979502</td>
		<td>0bb1e67655c7181e64315d56dd79d48a7a52f7e7a31f8da44c294d0a408874ec</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1120</td>
	</tr>
	<tr>
		<td>2024-06-25 13:53:43</td>
		<td>1952278</td>
		<td>0baa9da516a431676e1a326df9bde502504db87d69c5cadab13f51202c784f67</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1110</td>
	</tr>
	<tr>
		<td>2024-06-25 00:39:52</td>
		<td>1940364</td>
		<td>75825f6ed2e671cf0c50da51de567d1f0229f3663b76cf231d4115108577c2b8</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1105</td>
	</tr>
	<tr>
		<td>2024-06-26 11:06:14</td>
		<td>1971401</td>
		<td>502d5de3828565799a6ca98f1cc0702aa0940c702328189d3d099ea5828ea576</td>
		<td>BATCH_EU1_NOCTURNE_DEV</td>
		<td>-1102</td>
	</tr>

</table>

**Comment by HDauven** [comment] 2024-07-31 07:42
Duplicate of #1608

**Closed by HDauven** 2024-07-31 07:42 UTC
Labels: fix:bug
