### ISSUE TITLE
Cannot finalize txs: VM Error: Cannot allocate memory (os error 12) on raspberry pi

### ISSUE THREAD

**Issue by Daksh14** [dusk-network/rusk#1462] opened 2024-02-24 06:17 UTC
```2024-02-23T20:16:35.008491Z  INFO rusk::chain::vm: Received finalize request
2024-02-23T20:16:35.027082Z ERROR node::chain: event="fsm::on_event failed" src="wire" err="Cannot finalize txs: VM Error: Cannot allocate memory (os error 12)!!"
2024-02-23T20:16:35.027252Z  INFO node::chain: event="block received" src="wire" blk_height=1 blk_hash="14e337e59e93f691...ca13ff0f5aa2d01a"
2024-02-23T20:16:35.495517Z  WARN node::databroker: error on handling msg: could not find candidate
2024-02-23T20:16:35.585782Z  INFO rusk::chain::vm: Received finalize request
2024-02-23T20:16:35.602358Z ERROR node::chain: event="fsm::on_event failed" src="wire" err="Cannot finalize txs: VM Error: Cannot allocate memory (os error 12)!!"
2024-02-23T20:16:35.602790Z  INFO node::chain: event="block received" src="wire" blk_height=1 blk_hash="14e337e59e93f691...ca13ff0f5aa2d01a"
```

This is on raspberrypi ARM, the error is from the VM, should this error be made in the piecrust repo instead? 

It doesn't happen on macos, only on my raspberry pi ARM for now.

1gb ram raspberry pi 4 B

could it happen because of low RAM? I use htop and I don't see much ram or swap being used though

I compiled my binary mentioned here https://github.com/dusk-network/rusk/issues/1450

**Comment by HDauven** [comment] 2024-02-24 16:51
I'm not able to reproduce this on the Pi 5 with 8 GB RAM, with an ephemeral node.

I compiled both the wallet and Rusk locally. The WASM contracts were compiled on an ARM64 machine.

Are you proving locally? If so, that's going to be too tight with 1 GB RAM. I can also imagine it being an issue with mem pages.

CC: @ureeves

**Comment by HDauven** [comment] 2024-02-25 13:36
Currently got a Pi 5 node synced up and participating in consensus. It's using about ~1300 MB virtual RAM and ~500 MB reserved.
1 GB might just not be enough during bursts and with system allocation in mind. Would be nice to see it tested with 2GB.

Maybe @ureeves wants to chip in, else I think we can close this one.

**Comment by ureeves** [comment] 2024-02-26 09:06
> ```
> 2024-02-23T20:16:35.027082Z ERROR node::chain: event="fsm::on_event failed" src="wire" err="Cannot finalize txs: VM Error: Cannot allocate memory (os error 12)!!"
> 2024-02-23T20:16:35.027252Z  INFO node::chain: event="block received" src="wire" blk_height=1 blk_hash="14e337e59e93f691...ca13ff0f5aa2d01a"
> 2024-02-23T20:16:35.495517Z  WARN node::databroker: error on handling msg: could not find candidate
> 2024-02-23T20:16:35.585782Z  INFO rusk::chain::vm: Received finalize request
> 2024-02-23T20:16:35.602358Z ERROR node::chain: event="fsm::on_event failed" src="wire" err="Cannot finalize txs: VM Error: Cannot allocate memory (os error 12)!!"
> 2024-02-23T20:16:35.602790Z  INFO node::chain: event="block received" src="wire" blk_height=1 blk_hash="14e337e59e93f691...ca13ff0f5aa2d01a"
> ```
> 
> This is on raspberrypi ARM, the error is from the VM, should this error be made in the piecrust repo instead?
> 
> It doesn't happen on macos, only on my raspberry pi ARM for now.
> 
> 1gb ram raspberry pi 4 B
> 
> could it happen because of low RAM? I use htop and I don't see much ram or swap being used though
> 
> I compiled my binary mentioned here #1450

Being a bit pedantic here at first, but the [node requirements](https://docs.dusk.network/getting-started/node-setup/node-requirements) clearly state the need for better hardware, specifically 4GB RAM, so this is not really a bug since we specify that it won't work with less.

> Currently got a Pi 5 node synced up and participating in consensus. It's using about ~1300 MB virtual RAM and ~500 MB reserved. 1 GB might just not be enough during bursts and with system allocation in mind. Would be nice to see it tested with 2GB.
> 
> Maybe @ureeves wants to chip in, else I think we can close this one.

This further emphasizes that the amount of memory available is the problem rather than any issue related to architecture, so that's good news.

I realize this may not be what we want to hear, but it seems like the Raspberry PI 4b with 1GB of memory is simply not enough to run a node on.

**Closed** 2024-02-26 09:11 UTC
Labels: fix:bug
