### ISSUE TITLE
Rusk Schema: FilterTransactions to return state root

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/rusk#377] opened 2021-12-01 10:12 UTC
On the current diagram, we have `FilterTransactions(Tx[], block_gas_limit, block_height) -> Tx[]` to return a set of transactions that can be executed with the provided gas limit.

Currently, Rusk will execute these transactions and sum the consumed gas until the limit, so the subset of executed transactions can be returned. That way, we have a final state that is the `state_root`.

The state root is a requirement for the block candidate since it is part of the canonical block header (check specs). Therefore, it is useful if this function return this new state root considering that the candidate block will be built with the correct block hash.

```
Header
Dusk Network protocol header is a tuple H=(v,h,b,i,t,s,c).
...
| state_root | Hs | byte[32] | he root of the Patricia-Merkle Trie representing the latest state (after the application of the transactions included in the block) of the protocol
...
```

Since it will not return the filtered transactions but instead a tuple, and also execute the transactions instead of just selecting them, it is recommended we rename the function to `ExecuteStateTransition` in order to avoid confusion.

**Comment by vlopes11** [comment] 2021-12-01 10:14
As a note, we might keep or discard the generated Rusk state, considering also that is an implementation detail

**Comment by autholykos** [comment] 2021-12-21 10:48
This is actually part of #269. It stays as reference

**Comment by autholykos** [comment] 2022-01-21 09:14
Duplicate of #390

**Closed by autholykos** 2022-01-21 09:14 UTC
Labels: type:docs, mark:testnet
