### ISSUE TITLE
Allocate screen alignment issue

### ISSUE THREAD

**Issue by kieranhall** [dusk-network/rusk#2439] opened 2024-09-20 07:16 UTC
Small issue of this not being aligned 
![image](https://github.com/user-attachments/assets/591341ef-1bb3-4269-9781-c864db1cae0c)

_Originally posted by @deuch13 in https://github.com/dusk-network/rusk/issues/2426#issuecomment-2360965749_

**Comment by nortonandreev** [comment] 2024-09-20 07:21
Also related – https://github.com/dusk-network/rusk/issues/2433

I'm not sure if it's about the same or a different view.

**Comment by nortonandreev** [comment] 2024-09-23 10:35
Closing as a duplicate of #2433

**Closed by nortonandreev** 2024-09-23 10:35 UTC
Labels: fix:bug, module:web-wallet
